Fix wrong reference to Sitecore.Kernel
Sitecore.Kernel was pointing to '..\..\..\..\..\..\Repos\brunel-website\packages\Sitecore.Kernel.NoReferences.8.2.170728\lib\NET452\Sitecore.Kernel.dll' causing the build error 'error CS0234: The type or namespace name 'Diagnostics' does not exist in the namespace 'Sitecore''.

Changed reference to NuGet package folder.